metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["http://fastapi-app:8000"]
    metrics_path: /metrics
    metrics_filters:
      include: ["endpoint_hits_total"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"